return {
    Magic = {
        Zone1 = { name = "Unusual Room", multiplier = 3, requirement = "1K", cframe = CFrame.new() },
        Zone2 = { name = "Library", multiplier = 7.5, requirement = "15K", cframe = CFrame.new() },
        Zone3 = { name = "Abandoned House", multiplier = 15, requirement = "250K", cframe = CFrame.new() },
        Zone4 = { name = "Amethyst Cave", multiplier = 40, requirement = "5M", cframe = CFrame.new() },
        Zone5 = { name = "Cemetery Core", multiplier = 75, requirement = "100M", cframe = CFrame.new() },
        Zone6 = { name = "Haunted Hospital", multiplier = 150, requirement = "1.25B", cframe = CFrame.new() },
        Zone7 = { name = "Cursed Room", multiplier = 200, requirement = "25B", cframe = CFrame.new() },
        Zone8 = { name = "Bizzare Pool", multiplier = 375, requirement = "250B", cframe = CFrame.new() },
        Zone9 = { name = "Soul Room", multiplier = 750, requirement = "5T", cframe = CFrame.new() },
        Zone10 = { name = "Peak Dark Magic", multiplier = 1250, requirement = "25T", cframe = CFrame.new() },
        Zone11 = { name = "Dimensional Rift", multiplier = 1750, requirement = "150T", cframe = CFrame.new() },
        Zone12 = { name = "Magic Development Facility", multiplier = 2250, requirement = "1Qd", cframe = CFrame.new() },
        Zone13 = { name = "The Vortex", multiplier = 3000, requirement = "5Qd", cframe = CFrame.new() },
        Zone14 = { name = "Magic Temple", multiplier = 4500, requirement = "45Qd", cframe = CFrame.new() },
        Zone15 = { name = "Summoning Circle", multiplier = 5500, requirement = "175Qd", cframe = CFrame.new() },
        Zone16 = { name = "Ancient Crystal Ball", multiplier = 8000, requirement = "500Qd", cframe = CFrame.new() }
    }
}

