return {
    Magic = {
        Zone1  = { name = "Unusual Room", multiplier = 3, requirement = "1K", cframe = CFrame.new(-230.63, 126.90, 166.58) },
        Zone2  = { name = "Library", multiplier = 7.5, requirement = "15K", cframe = CFrame.new(-571.99, 75.95, -857.73) },
        Zone3  = { name = "Abandoned House", multiplier = 15, requirement = "250K", cframe = CFrame.new(1494.04, 65.33, -1824.30) },
        Zone4  = { name = "Amethyst Cave", multiplier = 40, requirement = "5M", cframe = CFrame.new(308.62, 198.23, -2112.87) },
        Zone5  = { name = "Cemetery Core", multiplier = 75, requirement = "100M", cframe = CFrame.new(2171.50, -1.84, 384.15) },
        Zone6  = { name = "Haunted Hospital", multiplier = 150, requirement = "1.25B", cframe = CFrame.new(1637.95, 35.76, -669.30) },
        Zone7  = { name = "Cursed Room", multiplier = 200, requirement = "25B", cframe = CFrame.new(1987.65, 28.56, 1090.00) },
        Zone8  = { name = "Bizzare Pool", multiplier = 375, requirement = "250B", cframe = CFrame.new(284.91, -2.39, -2544.66) },
        Zone9  = { name = "Soul Room", multiplier = 750, requirement = "5T", cframe = CFrame.new(179.30, -500.39, -2763.20) },
        Zone10 = { name = "Peak Dark Magic", multiplier = 1250, requirement = "25T", cframe = CFrame.new(-140.38, -579.95, -3023.85) },
        Zone11 = { name = "Dimensional Rift", multiplier = 1750, requirement = "150T", cframe = CFrame.new(-40.54, -625.16, -1990.33) },
        Zone12 = { name = "Magic Development Facility", multiplier = 2250, requirement = "1Qd", cframe = CFrame.new(2560.03, 60.55, 2115.48) },
        Zone13 = { name = "The Vortex", multiplier = 3000, requirement = "5Qd", cframe = CFrame.new(-563.40, -1442.79, -3438.59) },
        Zone14 = { name = "Magic Temple", multiplier = 4500, requirement = "45Qd", cframe = CFrame.new(-819.28, -1451.00, -2164.04) },
        Zone15 = { name = "Summoning Circle", multiplier = 5500, requirement = "175Qd", cframe = CFrame.new(-485.50, -1437.08, -3673.12) },
        Zone16 = { name = "Ancient Crystal Ball", multiplier = 8000, requirement = "500Qd", cframe = CFrame.new(-593.74, 2126.79, -3279.30) }
    }
}
